/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class k15games_engine_launcher_LauncherThread */

#ifndef _Included_k15games_engine_launcher_LauncherThread
#define _Included_k15games_engine_launcher_LauncherThread
#ifdef __cplusplus
extern "C" {
#endif
#undef k15games_engine_launcher_LauncherThread_MIN_PRIORITY
#define k15games_engine_launcher_LauncherThread_MIN_PRIORITY 1L
#undef k15games_engine_launcher_LauncherThread_NORM_PRIORITY
#define k15games_engine_launcher_LauncherThread_NORM_PRIORITY 5L
#undef k15games_engine_launcher_LauncherThread_MAX_PRIORITY
#define k15games_engine_launcher_LauncherThread_MAX_PRIORITY 10L
/*
 * Class:     k15games_engine_launcher_LauncherThread
 * Method:    K15_RunEngine
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_k15games_engine_launcher_LauncherThread_K15_1TickEngine
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     k15games_engine_launcher_LauncherThread
 * Method:    K15_InitEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_k15games_engine_launcher_LauncherThread_K15_1InitEngine
  (JNIEnv *, jobject);

/*
 * Class:     k15games_engine_launcher_LauncherThread
 * Method:    K15_ShutdownEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_k15games_engine_launcher_LauncherThread_K15_1ShutdownEngine
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
