#ifndef _K15_Rendering_ShaderSemantics_h_
#define _K15_Rendering_ShaderSemantics_h_

#include "K15_RenderPrerequisites.h"

//semantic groups
#define K15_SEMANTIC_GROUP_ID_PER_OBJECT 1
#define K15_SEMANTIC_GROUP_ID_PER_MATERIAL 2

//uniforms
#define K15_SEMANTIC_MODEL_VIEW_PROJECTION_MATRIX_ID 1
#define K15_SEMANTIC_MODEL_MATRIX_ID 2
#define K15_SEMANTIC_DATA_ID 3

//attributes
#define K15_SEMANTIC_POSITION_ID 5
#define K15_SEMANTIC_NORMAL_ID 6
#define K15_SEMANTIC_TEXCOORD1_ID 7
#define K15_SEMANTIC_TEXCOORD2_ID 8
#define K15_SEMANTIC_TEXCOORD3_ID 9
#define K15_SEMANTIC_TEXCOORD4_ID 10
#define K15_SEMANTIC_TEXCOORD5_ID 11
#define K15_SEMANTIC_TEXCOORD6_ID 12
#define K15_SEMANTIC_TEXCOORD7_ID 13
#define K15_SEMANTIC_TEXCOORD8_ID 14
#define K15_SEMANTIC_COLOR1_ID 15
#define K15_SEMANTIC_COLOR2_ID 16
#define K15_SEMANTIC_COLOR3_ID 17
#define K15_SEMANTIC_COLOR4_ID 18

#define K15_SEMANTIC_MODEL_VIEW_PROJECTION_MATRIX_VARIABLE_NAME "g_MVPMatrix"
#define K15_SEMANTIC_MODEL_MATRIX_VARIABLE_NAME "g_ModelMatrix"

#define K15_SEMANTIC_MODEL_VIEW_PROJECTION_MATRIX_SEMANTIC_NAME "MVPMATRIX"
#define K15_SEMANTIC_MODEL_MATRIX_SEMANTIC_NAME "MODELMATRIX"
#define K15_SEMANTIC_DATA_SEMANTIC_NAME "DATA"

#define K15_SEMANTIC_POSITION_SEMANTIC_NAME "POSITION"
#define K15_SEMANTIC_NORMAL_SEMANTIC_NAME "NORMAL"
#define K15_SEMANTIC_TEXCOORD1_SEMANTIC_NAME "TEXCOORD0"
#define K15_SEMANTIC_TEXCOORD2_SEMANTIC_NAME "TEXCOORD1"
#define K15_SEMANTIC_TEXCOORD3_SEMANTIC_NAME "TEXCOORD2"
#define K15_SEMANTIC_TEXCOORD4_SEMANTIC_NAME "TEXCOORD3"
#define K15_SEMANTIC_TEXCOORD5_SEMANTIC_NAME "TEXCOORD4"
#define K15_SEMANTIC_TEXCOORD6_SEMANTIC_NAME "TEXCOORD5"
#define K15_SEMANTIC_TEXCOORD7_SEMANTIC_NAME "TEXCOORD6"
#define K15_SEMANTIC_TEXCOORD8_SEMANTIC_NAME "TEXCOORD7"
#define K15_SEMANTIC_COLOR1_SEMANTIC_NAME "COLOR0"
#define K15_SEMANTIC_COLOR2_SEMANTIC_NAME "COLOR1"
#define K15_SEMANTIC_COLOR3_SEMANTIC_NAME "COLOR2"
#define K15_SEMANTIC_COLOR4_SEMANTIC_NAME "COLOR3"

#define K15_TYPE_INT_ID 1
#define K15_TYPE_FLOAT_ID 2
#define K15_TYPE_FLOAT_VECTOR2_ID 3
#define K15_TYPE_FLOAT_VECTOR3_ID 4
#define K15_TYPE_FLOAT_VECTOR4_ID 5
#define K15_TYPE_FLOAT_MATRIX2_ID 6
#define K15_TYPE_FLOAT_MATRIX3_ID 7
#define K15_TYPE_FLOAT_MATRIX4_ID 8
#define K15_TYPE_SAMPLER_2D_ID 9
#define K15_TYPE_TEXTURE_2D_ID 10

#define K15_TYPE_INT_NAME "int"
#define K15_TYPE_FLOAT_NAME "float"
#define K15_TYPE_FLOAT_VECTOR2_NAME "K15_Vector2"
#define K15_TYPE_FLOAT_VECTOR3_NAME "K15_Vector3"
#define K15_TYPE_FLOAT_VECTOR4_NAME "K15_Vector4"
#define K15_TYPE_FLOAT_MATRIX2_NAME "K15_Matrix2"
#define K15_TYPE_FLOAT_MATRIX3_NAME "K15_Matrix3"
#define K15_TYPE_FLOAT_MATRIX4_NAME "K15_Matrix4"
#define K15_TYPE_SAMPLER_2D_NAME "K15_2DSampler"
#define K15_TYPE_TEXTURE_2D_NAME "K15_2DTexture"

#endif //_K15_Rendering_ShaderSemantics_h_