#ifndef _K15_ErrorCodes_h_
#define _K15_ErrorCodes_h_

#include "K15_Prerequisites.h"

#define K15_SUCCESS 0

#define K15_SYSTEM_EVENT_QUEUE_FULL 100
#define K15_SYSTEM_EVENT_QUEUE_EMPTY 101

#define K15_OS_ASYNC_IO_QUEUED 150

#define K15_OS_ERROR_SYSTEM										200
#define K15_OS_ERROR_MONITOR_NOT_FOUND							201
#define K15_OS_ERROR_RESOLUTION_NOT_SUPPORTED					202
#define K15_OS_ERROR_OUT_OF_MEMORY								203
#define K15_OS_ERROR_NO_WINDOW									204
#define K15_OS_ERROR_FILE_NOT_FOUND								205
#define K15_OS_ERROR_THREAD_ALREADY_STARTED						206
#define K15_OS_ERROR_THREAD_NOT_JOINABLE						207
#define K15_OS_TIMEOUT											208
#define K15_OS_ERROR_LIBRARY_NOT_LOADED							209
#define K15_OS_ERROR_DYNAMIC_LIBRARY_NOT_LOADED					210
#define K15_OS_ERROR_DYNAMIC_LIBRARY_NOT_RELOADABLE				211
#define K15_OS_ERROR_EMPTY_FILE									212
#define K15_OS_ERROR_RENDER_CONTEXT_ALREADY_CREATED				213

#define K15_ERROR_MAX_RENDER_COMMAND_QUEUE_REACHED				110
#define K15_ERROR_MAX_RENDER_COMMAND_BUFFER_FULL				111
#define K15_ERROR_NO_RENDER_COMMAND								112
#define K15_ERROR_MAX_COMMAND_PARAMETER_SIZE_BUFFER_REACHED		113
#define K15_ERROR_RENDER_COMMAND_NOT_IMPLEMENTED				114
#define K15_ERROR_INVALID_PARAMETER_SIZE						115
#define K15_ERROR_INVALID_BUFFER_TYPE							116
#define K15_ERROR_LAST_COMMAND_NOT_FINISHED						117
#define K15_ERROR_RENDER_BUFFER_LOCKED							118
#define K15_ERROR_RENDER_API									119
#define K15_ERROR_RENDER_PROGRAM_COMPILATION					120
#define K15_ERROR_RENDER_UNIFORM_NOT_FOUND						121
#define K15_ERROR_RENDER_COMMAND_QUEUE_ALREADY_DISPATCHED		122
#define K15_ERROR_TOO_MANY_TEXTURES_ACTIVE						123

#ifdef K15_LOG_ON_RESULT_CHECK
	#define K15_CHECK_RESULT(result) {result8 r = result; if (r != K15_SUCCESS) { \
	K15_LOG_WARNING_MESSAGE("Function '%s' exited with result '%s'.", #result, K15_GetErrorCodeString(r));}}

#else
	#define K15_CHECK_RESULT(result) result
#endif //K15_LOG_ON_RESULT_CHECK

const char* K15_GetErrorCodeString(result8 p_Result);

#endif //_K15_ErrorCodes_h_
