set(OGL_SRC "./src/K15_OpenGL_GpuBufferImpl.cpp"
"./src/K15_OpenGL_GpuProgramBatchImpl.cpp"
"./src/K15_OpenGL_GpuProgramImpl.cpp"
"./src/K15_OpenGL_Renderer.cpp"
"./src/K15_OpenGL_TextureImpl.cpp"
"./src/K15_OpenGL_TextureSamplerImpl.cpp"
"./src/K15_OpenGL_VertexDeclarationImpl.cpp"
"./src/WGL/K15_OpenGL_WGL.cpp"
"./src/GLX/K15_OpenGL_GLX.cpp"
"./src/plugin.cpp")

set(OGL_INC "./include/K15_OpenGL_GpuBufferImpl.h"
"./include/K15_OpenGL_GpuProgramBatchImpl.h"
"./include/K15_OpenGL_GpuProgramImpl.h"
"./include/K15_OpenGL_Prerequisites.h"
"./include/K15_OpenGL_Renderer.h"
"./include/K15_OpenGL_TextureImpl.h"
"./include/K15_OpenGL_TextureImpl.inl"
"./include/K15_OpenGL_TextureSamplerImpl.h"
"./include/K15_OpenGL_TextureSamplerImpl.inl"
"./include/K15_OpenGL_VertexDeclarationImpl.h"
"./include/WGL/K15_OpenGL_WGL.h"
"./include/GLX/K15_OpenGL_GLX.h"
"./include/plugin.h")
