#ifndef _K15_Rendering_GL_Config_h_
#define _K15_Rendering_GL_Config_h_

#define K15_OPENGL_ENABLE_ERROR_CHECK_CALLS
#define K15_OPENGL_ENABLE_INVALIDATE_MAP_BUFFER_RANGE

//undef do not create a debug context
#define K15_OPENGL_CREATE_DEBUG_CONTEXT
#define K15_OPENGL_FORCE_ES_2_0_CONTEXT
#define K15_OPENGL_FORCE_ES_3_0_CONTEXT
#define K15_OPENGL_FORCE_ES_3_1_CONTEXT
#define K15_OPENGL_FORCE_ES_3_2_CONTEXT

//#define K15_OPENGL_ENABLE_QUAD_BUFFER_BACKUP

#define K15_RENDER_GL_MAX_OBJECTS 4096
#define K15_RENDER_GL_MAX_PENDING_BUFFER_UPDATES 1024
#define K15_RENDER_GL_DEFAULT_VERTEX_CACHE_ENTRY_SIZE size_megabyte(5)

#define K15_RENDER_GL_MAX_COLOR_ATTACHMENTS 8
#define K15_RENDER_GL_MAX_VERTEX_CACHE_ENTRIES 1024

#define K15_GL_TRANSPOSE_MATRIX 0

#define K15_GL_INVALID_TEXTURE_SLOT 0xFFFFFFFF

#define K15_RENDER_GL_MAX_PROGRAM_UNIFORMS 64
#define K15_RENDER_GL_MAX_INCLUDE_FILE_SIZE 32
#define K15_RENDER_GL_MAX_VERTEX_FORMAT_CACHE_SIZE 64
#define K15_RENDER_GL_MAX_SHADER_CODE_SIZE size_kilobyte(512)
#define K15_RENDER_GL_MAX_INCLUDE_FILES 64
#define K15_RENDER_GL_MAX_DEFINES 64
#define K15_RENDER_GL_MAX_DEFINE_NAME_SIZE 128

#define K15_RENDER_GL_PVRTC_FLAG 0x01
#define K15_RENDER_GL_DXT_1_FLAG 0x02
#define K15_RENDER_GL_DXT_3_FLAG 0x04
#define K15_RENDER_GL_DXT_5_FLAG 0x08
#define K15_RENDER_GL_3DC_FLAG	 0x10
#define K15_RENDER_GL_ATC_FLAG	 0x20


#endif //_K15_Rendering_GL_Config_h_
