set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/libs")

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

add_subdirectory(assimp)
add_subdirectory(detour)
add_subdirectory(enet)
#add_subdirectory(freetype)
add_subdirectory(glew)
add_subdirectory(jsoncpp)
add_subdirectory(minizip)
add_subdirectory(zlib)
add_subdirectory(ois)
add_subdirectory(tinythread)
add_subdirectory(math)
add_subdirectory(logging)
add_subdirectory(os_layer)
#add_subdirectory(tinyxml)
add_subdirectory(squish)
add_subdirectory(luajit)
add_subdirectory(resourceformats)

set_target_properties(assimp PROPERTIES FOLDER dependencies)
set_target_properties(detour PROPERTIES FOLDER dependencies)
set_target_properties(enet PROPERTIES FOLDER dependencies)
set_target_properties(glew PROPERTIES FOLDER dependencies)
set_target_properties(jsoncpp PROPERTIES FOLDER dependencies)
set_target_properties(minizip PROPERTIES FOLDER dependencies)
set_target_properties(zlib PROPERTIES FOLDER dependencies)
set_target_properties(ois PROPERTIES FOLDER dependencies)
set_target_properties(tinythread PROPERTIES FOLDER dependencies)
set_target_properties(k15math PROPERTIES FOLDER dependencies)
set_target_properties(squish PROPERTIES FOLDER dependencies)
set_target_properties(luajit PROPERTIES FOLDER dependencies)
set_target_properties(resourceformats PROPERTIES FOLDER dependencies)
set_target_properties(buildvm PROPERTIES FOLDER tools)
set_target_properties(minilua PROPERTIES FOLDER tools)
