set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/libs")

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

add_subdirectory(assimp)
add_subdirectory(detour)
add_subdirectory(enet)
add_subdirectory(zlib)
add_subdirectory(squish)
add_subdirectory(luajit)

set_target_properties(assimp PROPERTIES FOLDER dependencies)
set_target_properties(detour PROPERTIES FOLDER dependencies)
set_target_properties(enet PROPERTIES FOLDER dependencies)
set_target_properties(zlib PROPERTIES FOLDER dependencies)
set_target_properties(squish PROPERTIES FOLDER dependencies)
set_target_properties(luajit PROPERTIES FOLDER dependencies)
set_target_properties(buildvm PROPERTIES FOLDER tools)
set_target_properties(minilua PROPERTIES FOLDER tools)
