#!/bin/sh

LOCAL_DIR=$(pwd)
BUILD_CMD="ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=Application.mk"
BIN_DIR=$LOCAL_DIR/../bin/Android/

cd $LOCAL_DIR/Dependencies/JsonCPP
eval $BUILD_CMD


cd $LOCAL_DIR/Dependencies/Enet
eval $BUILD_CMD


cd $LOCAL_DIR/Dependencies/TinyThread
eval $BUILD_CMD

#create binary dir if it doesnt exist.
if [ ! -d $BIN_DIR ]; then
	mkdir $LOCAL_DIR/../bin/Android/
fi

mv -f $LOCAL_DIR/Dependencies/JsonCPP/obj/local/armeabi/*.a $LOCAL_DIR/../bin/Android/ 
mv -f $LOCAL_DIR/Dependencies/Enet/obj/local/armeabi/*.a $LOCAL_DIR/../bin/Android/
mv -f $LOCAL_DIR/Dependencies/TinyThread/obj/local/armeabi/*.a $LOCAL_DIR/../bin/Android/