#ifndef _K15_Rendering_GL_Config_h_
#define _K15_Rendering_GL_Config_h_

#define K15_OPENGL_ENABLE_ERROR_CHECK_CALLS
#define K15_OPENGL_ENABLE_INVALIDATE_MAP_BUFFER_RANGE
//#define K15_OPENGL_ENABLE_QUAD_BUFFER_BACKUP

#ifdef K15_DEBUG
	#define K15_OPENGL_CREATE_DEBUG_CONTEXT
#endif //K15_DEBUG

#define K15_RENDER_GL_MAX_BUFFER_COUNT 32
#define K15_RENDER_GL_BUFFER_SIZE size_megabyte(10)

#define K15_RENDER_GL_MAX_RENDER_TARGET_COUNT 32
#define K15_RENDER_GL_MAX_COLOR_ATTACHMENTS 8

#define K15_GL_TRANSPOSE_MATRIX 0

#define K15_RENDER_GL_MAX_PROGRAM_UNIFORMS 64
#define K15_RENDER_GL_MAX_INCLUDE_FILE_SIZE 32
#define K15_RENDER_GL_MAX_SHADER_CODE_SIZE size_kilobyte(512)
#define K15_RENDER_GL_MAX_INCLUDE_FILES 64
#define K15_RENDER_GL_MAX_DEFINES 64
#define K15_RENDER_GL_MAX_DEFINE_NAME_SIZE 128

#endif //_K15_Rendering_GL_Config_h_
