#ifndef _K15_Rendering_GL_Config_h_
#define _K15_Rendering_GL_Config_h_

#define K15_OPENGL_ENABLE_ERROR_CHECK_CALLS
#define K15_OPENGL_ENABLE_INVALIDATE_MAP_BUFFER_RANGE

#endif //_K15_Rendering_GL_Config_h_
